version: "3.9"

services:
  web:
    build: .
    env_file: .env
    volumes:
      - media_volume:/app/media
      - backups_volume:/backups
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16
    env_file: .env
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_backup_device:/var/lib/postgresql/data

volumes:
  media_volume:
  backups_volume:
  pgdata_backup_device:

networks:
  backend:
    driver: bridge
